# SmallFile workload using https://github.com/distributed-system-analysis/smallfile
# smallfile is a python-based distributed POSIX workload generator which can be
# used to quickly measure performance for a variety of metadata-intensive
# workloads
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: smallfile-benchmark
  namespace: my-ripsaw
spec:
  test_user: avi-liani
  clustername: dc27-4.4-on-4.3
  elasticsearch:
    server: 10.0.144.152
    port: 9200
  es_index: ripsaw_smallfile
  metadata_collection: true
  index_data: true
  workload:
    name: smallfile
    args:
      clients: 1
      samples: 1
      pause: 50
      operation: ["cleanup","create","read","append", "delete"]
      threads: 4
      file_size: 64
      files: 50000
      storageclass: ocs-storageclass-ceph-rbd
      storagesize: 100Gi
