apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: fio-benchmark
  namespace: my-ripsaw
spec:
  elasticsearch:
    server: 10.0.78.167
    port: 9200
    parallel: true
  clustername: env_ocpversion_ocsversion
  test_user: interface_iopattern
  workload:
    name: "fio_distributed"
    args:
      prefill: true
      samples: 3
      servers: 5
      pin_server: ''
      jobs:
        - randwrite
        - randread
      bs:
        - 1024KiB
      numjobs:
        - 1
      iodepth: 16
      read_runtime: 300
      write_runtime: 300
      read_ramp_time: 5
      write_ramp_time: 5
      filesize: 10GiB
      log_sample_rate: 30000
      storageclass: ocs-storagecluster-ceph-rbd-cmp
      storagesize: 12Gi
#      rook_ceph_drop_caches: True
#      rook_ceph_drop_cache_pod_ip:
#######################################
#  EXPERT AREA - MODIFY WITH CAUTION  #
#######################################
#  global_overrides:
  job_params:
    - jobname_match: write
      params:
        - time_based=1
        - fsync_on_close=1
        - refill_buffers=1
        - runtime={{ workload_args.write_runtime }}
        - ramp_time={{ workload_args.write_ramp_time }}
        - buffer_compress_percentage=60 # 0 and 60 worst case/fair case
        - buffer_pattern=0xdeadface
    - jobname_match: read
      params:
        - time_based=1
        - runtime={{ workload_args.read_runtime }}
        - ramp_time={{ workload_args.read_ramp_time }}
    - jobname_match: readwrite
      params:
        - rwmixread=50
        - time_based=1
        - runtime={{ workload_args.read_runtime }}
        - ramp_time={{ workload_args.read_ramp_time }}
        - buffer_compress_percentage=60 # 0 and 60 worst case/fair case
        - buffer_pattern=0xdeadface
    - jobname_match: randread
      params:
        - time_based=1
        - randrepeat=0
        - allrandrepeat=0
        - runtime={{ workload_args.read_runtime }}
        - ramp_time={{ workload_args.read_ramp_time }}
    - jobname_match: randwrite
      params:
        - time_based=1
        - randrepeat=0
        - allrandrepeat=0
        - runtime={{ workload_args.write_runtime }}
        - ramp_time={{ workload_args.write_ramp_time }}
        - buffer_compress_percentage=60 # 0 and 60 worst case/fair case
        - buffer_pattern=0xdeadface
    - jobname_match: randrw
      params:
        - time_based=1
        - randrepeat=0
        - allrandrepeat=0
        - rwmixread=50
        - runtime={{ workload_args.write_runtime }}
        - ramp_time={{ workload_args.write_ramp_time }}
        - buffer_compress_percentage=60 # 0 and 60 worst case/fair case
        - buffer_pattern=0xdeadface
    - jobname_match: rw
      params:
        - rwmixread=30
        - time_based=1
        - runtime={{ workload_args.read_runtime }}
        - ramp_time={{ workload_args.read_ramp_time }}
        - refill_buffers=1
        - buffer_compress_percentage=60 # 0 and 60 worst case/fair case
        - buffer_pattern=0xdeadface
