---
#RUN:
  #client_version: '4.3.0-0.nightly'
DEPLOYMENT:
  # TODO: update to false when supported
  allow_lower_instance_requirements: true
  #installer_version: "4.3.0-0.nightly"
ENV_DATA:
  platform: 'vsphere'
  deployment_type: 'upi'
  worker_replicas: 4
  master_replicas: 3
  # TODO: update worker_num_cpus to 16 when supported
  worker_num_cpus: '12'
  master_num_cpus: '4'
  memory: '65536'
  #vm_template: 'rhcos-4.3.0-x86_64-vmware'
